### ISSUE TITLE
Photo essay funkiness

### ISSUE THREAD

**Issue by halfempty** [halfempty/coveredwithfur#11]
http://www.astrangeobject.com/cwf/storefront-property-katie-smither/

**Comment by halfempty** [comment]
@JShapland I've swapped-out the slideshow mechanism for a new one. You'll see there's a new field on the edit screen for Galleries, which is hopefully obvious and intuitive to use. On the front-end, the display is pretty much how it comes out-of-the-box, but we can customize it if you like. 

Please take a look:

http://www.astrangeobject.com/cwf/storefront-property-katie-smither/

**Comment by JShapland** [comment]
I think it looks good, @halfempty ! Only question I have is about the text below the slideshow, which is now pushed to the right instead of centered.

**Comment by halfempty** [comment]
@JShapland Okay, captions are now centered

**Comment by JShapland** [comment]
Oops, I was unclear--I was hoping to center the body text below the
slideshow, not the captions.

On Sat, Oct 25, 2014 at 1:02 PM, Marty Spellerberg <notifications@github.com

> wrote:
> 
> @JShapland https://github.com/JShapland Okay, captions are now centered
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/halfempty/coveredwithfur/issues/11#issuecomment-60491240
> .

## 

Jenn Shapland
Digital Editor, Nonfiction
_www.astrangeobject.com http://www.astrangeobject.com/_
